on:
  push:
    branches: [ "feat/browser-embed" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: cargo build --release --target wasm32-unknown-unknown
      - name: package
        run: wasm32-bindgen --out-dir ./out/ --target web ./target/
      - name: publish-pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${CF_ACCOUNT_ID}
          projectName: browser-sph
          directory: .
