name: linux-push

on:
  push:
    branches: [ "**" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      CARGO_TERM_COLOR: always

    steps:
    - uses: actions/checkout@v3
    - name: set-up
      run: sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev
    - name: check-formatting
      run: cargo fmt --check --verbose
    - name: build-app
      run: cargo build --release --verbose
    - name: run-tests
      run: cargo test --release --verbose

