name: windows-test

on:
  push:
    branches: [ "**" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    env:
      CARGO_TERM_COLOR: always

    steps:
    - uses: actions/checkout@v3
    - name: check-formatting
      run: cargo fmt --check --verbose
    - name: build-app
      run: cargo build --release --verbose
    - name: run-tests
      run: cargo test --release --verbose
 